'use strict';
module.exports = {
    SUCCESS_CODE: 200,
    ERROR_CODE: 401,
    NOT_FOUND_ERROR_CODE: 402,
    NOT_FOUND_TOKEN: 403,
    INTERNAL_ERROR: 'Request could not be processed. Please try again.',
    INVALID_ID: 'Invalid Object Id',
    DATA_NOT_FOUND_CODE: 404,
    //Auth Ctrl
    EMAIL_ALREADY_EXIST: 'Email already exist.',
    INVALID_EMAIL: 'Email is not valid.',
    ACCOUNT_REGISTERED: 'Congratulations, your account has been registered successfully.',
    USER_NO_LONGER_EXIST: 'User no longer exist.',
    SENT_VERIFICATION_EMAIL: 'Verification email has been sent to your email.',
    FAILED_VERIFICATION_EMAIL: 'Verification email sending failed so please try again.',
    ACCOUNT_DELETED: 'Your account has been deleted.',
    ACCOUNT_INACTIVE: 'Your account not activated yet.',
    EMAIL_NOT_VERIFIED: "Your email is not verified yet.",
    SIGNIN_SUCCESS: 'User logged in successfully.',
    EMAIL_INCORRECT: 'No account with that email address exists.',
    ACCOUNT_ACTIVATED: 'Your account has been activated successfully.',
    ACCOUNT_ALREADY_ACTIVATED: 'Your account is already activated.',
    LOGIN_REQUIRED_FIELDS: 'Email and password is required.',
    INVALID_LOGIN_DETAILS: 'Email/password is not correct.',
    SENT_FORGOT_EMAIL_FAILED: 'Forgot email sending failed. Please try again.',
    SENT_FORGOT_EMAIL: 'An email has been sent to you with further instruction. So please check your email and reset password.',
    PASSWORD_RESET_TOKEN_EXPIRED: 'Password reset token is invalid or has expired.',
    PASSWORD_RESET_TOKEN_VALID: 'Password reset token is valid.',
    PASSWORD_RESET: 'Password has been reset successfully.',
    EMAIL_TEMPLATE_ADD: "Email template added successfully",
    EMAIL_TEMPLATE_UDATE: "Email template updated successfully",
    EMAIL_TEMPLATE_LIST: "Email template fetched successfully",
    INVALID_EMAIL_TEMPLATE_ID: "Inavlid Email template id",
    EMAIL_TEMPLATE_SEND: "EmailDetails added and mail send successfully",
    EMAIL_TEMPLATE_ERROR: "EmailDetails added successfully! Error while sending mail",
    INVALID_TEMPLATE: "Inavlid template id",
    //Dashboard Ctrl
    TASKS_LIST_FETCHED: 'Tasks list fetched successfully.',
    OPPORTUNITY_LIST_FETCHED: 'Opportunity list fetched successfully.',
    ESTIMATES_LIST_FETCHED: 'Estimates list fetched successfully.',
    PROJECTS_LIST_FETCHED: 'Projects list fetched successfully.',
    ORDERS_LIST_FETCHED: 'Orders list fetched successfully.',
    INVOICES_LIST_FETCHED: 'Invoices list fetched successfully.',
    GOALS_LIST_FETCHED: 'Goals list fetched successfully.',
    RECORD_NOT_FOUND: 'Record not found',
    //Contact controller
    ADD_CONTACT_SUCCESS: 'Contact/Company info added successfully',
    UPDATE_CONTACT_SUCCESS: 'Contact info updated successfully',
    UPDATE_CONTACT_LINK_SUCCESS: 'Contact links updated successfully',
    CONTACT_LIST_FETCHED: 'Contact list fetched successfully.',
    CONTACT_LINKS_FETCHED: 'Contact links fetched successfully.',
    CONTACT_LINKS_REMOVED: 'Contact links removed successfully.',
    CONTACT_DELETE: 'Contact/Company deleted successfully.',
    CONTACT_ADDED_GROUP_SUCCESS: 'Contact added to group successfully.',
    CONTACT_REMOVED_GROUP_SUCCESS: 'Contact removed from group successfully.',
    ADDED_GROUP_SUCCESS: 'Group added successfully.',
    GROUP_ALREADY_EXIST: 'Group already exist',
    FIELD_REQUIRED: 'Required fields are missing',
    CONTACT_TYPE_EXIST: 'Type already exist',
    CONTACT_STATUS_EXIST: 'Status already exist',
    CONTACT_SOURCE_EXIST: 'Source already exist',
    CONTACT_DEPARTMENT_EXIST: 'Department already exist',
    CONTACT_INDUSTRY_EXIST: 'Industry already exist',
    KEYWORD_EXIST: 'Keyword already exist',
    INVALID_COMPANY: 'Contact company not exist please create it first',
    CONTACT_DEPARTMENT_DELETED: 'Contact Department deleted succesfully.',
    CONTACT_INDUSTRY_DELETED: 'Contact Industry deleted succesfully.',
    //Users Ctrl
    UPDATE_USER_PROFILE_SUCCESS: 'Profile info updated successfully.',
    UPDATE_PROFILE_PIC_SUCCESS: 'User profile pic updated successfully.',
    REQUIRED_USERID: 'User Identification Id is required.',
    USER_RECORD_FETCHED: 'User info fetched successfully.',
    PASSWORD_CHANGED_SUCCESS: 'Password has been changed successfully.',
    WRONG_CURRENT_PASSWORD: 'Please provide correct current password.',
    PASSWORD_CANNOT_SAME_WITH_CURRENT_PASSWORD: 'Current password and new password cannot same.',
    REQUIRED_PASSWORD_VALUE: 'Current and New password are required.',
    USERS_LIST_FETCHED: 'Users list fetched successfully.',
    USER_IMAGE_FETCHED: 'User image fetched successfully.',
    EMAIL_OR_COMPANY_INCORRECT: 'Either email or company is not correct',
    USER_PIC_UPDATED: 'User profile pic updated successfully.',
    CHANGE_EMAIL_NOT_EXIST: 'Changed Email no longer exist',
    PASSWORD_NOT_AVAILABLE: 'Password not available',
    NEW_EMAIL_ALREADY_VERIFIED: "New email already verified.",
    //Company Ctrl
    COMPANY_ALREADY_EXIST: 'Account/Company with same name already exist.',
    ADD_COMPANY_SUCCESS: 'Account/Company added successfully.',
    ADD_COMPANY_REQUIRED_FIELDS: 'Account/Company name is required.',
    COMPANY_DETAILS_FETCHED: 'Account/Company User Details fetched successfully.',
    CONPANY_NO_LONGER_EXIST: 'Account/Company no longer exists',
    COMPANY_LIST_FETCHED: 'Account/Company list fetched successfully.',
    COMPANY_NOT_FOUND: 'Account/Company not found.',
    UPDATE_COMPANY_INFO_SUCCESS: 'Account/Company info updated successfully.',
    COMPANY_SELECTED: 'Account/Company selected successfully.',
    CONTACT_PIC_UPDATED: 'Profile pic updated successfully.',
    //Company User Ctrl
    ALREADY_INVITED_USER: 'This user is already invited.',
    USER_INVITE_SUCCESS: 'Invite Sent, The user will receive the invite at email address ',
    USER_EMAIL_FAILED: 'Opps something went wrong to send email so please try to re-send email.',
    COMPANY_USERS_LIST_FETCHED: 'Account/Company users list fetched successfully.',
    COMPANY_USERS_NOT_AVAIALBLE: 'Company Users not available.',
    FETCHED_COMPANY_USER_DETAILS: 'Company User Details fetched successfully.',
    INVITATION_ACCEPTED: 'Invitation has been accepted successfully.',
    COMPANY_USER_DELETED: 'User has been deleted successfully.',
    COMPANY_USER_PROFILE_UPDATED: 'Profile info updated successfully.',
    RESENT_INVITATION_SUCCESS: 'Invitation has been re-sent successfully.',
    RESET_COMPANY_USER_PASSWORD: 'A new password has been sent to your email. So Please check your inbox for new password.',
    RESET_PASSWORD_EMAIL_FAILED: 'Opps something went wrong to send email so please try to re-send email.',
    GET_COMPANY_USER_DETAILS: 'User details fetched successfully.',
    INVITE_NO_LONGER_EXIST: 'Invite no longer exists.',
    // User Activity Ctrl
    ACTIVITY_ADDED_SUCCESS: 'User activity added successfully.',
    USER_ACTIVITY_FETCHED: 'User activity fetched successfully.',
    USER_ACTIVITY_CATEGORY_ADD: 'Activity category added successfully.',
    ACTIVITY_DELETE_SUCCESS: 'Activity deleted successfully',
    COMPANY_ALL_USERS_ACTIVITY_FETCHED: 'Company user activity fetched successfully.',
    CATEGORY_LIST_FETCHED: 'Category list fetched successfully.',
    COMPANY_LISTCONTACT_FETCHED: 'User company contact fetched successfully',
    DATA_NOT_FOUND: 'Record not found',
    OPPORTUNITY_ADDED_SUCCESS: 'Opportunity created successfully',
    SALESREP_DATA: 'Sales rep fetched successfully',
    INDIVIDUAL_DATA: 'Individual list fetched successfully',
    OPPERTUNITY_FETCHED: 'Opportunity list fetched successfully',
    OPPORTUNITY_UPDATE_SUCCESS: 'Opportunity updated successfully',
    OPPORTUNITY_DELETE_SUCCESS: 'Opportunity deleted successfully',
    COMPANY_ID_MISSING: "Required field company id is missing or not a valid id",
    INVALID_CONTACT_ID: "Inavlid contact id",
    REQUIRED_FILED_MISSING: "Required field missing",
    REQUIRE_FILED_CONFIGURATION: "Required field empty",
    INVALID_OBJECT: "Provided objectId is not valid",
    CONTACT_CATEGORY_EXIST: "Category already exist",
    GROUP_DELETE: "Group deleted successfully",
    COMPANY_CONTACT_ID_MISSING: "Required field companyId and contactId is missing or not a valid id",
    INVALID_COMPANY_ID: "Inavlid company id",
    INVALID_ACTIVITY_TYPE: "Invalid activity type",
    INVALID_ESTIMATION: "Inavlid estimation id",
    ACTIVITY_DETAIL_BY_PROJECT: "Activity details by project fetched successfully",
    //Project module
    PROJECT_LIST: "Project list fetched successfully",
    PROJECT_DAILY_ADD: "Project daily report saved successfully",
    PROJECT_DAILY: "Project daily report list fetched  successfully",
    DAILYREPORT_DELETE_SUCCESS: "Daily report deleted succesfully",
    //Order module
    ORDER_LIST: "Order list fetched successfully",
     ORDER_TYPE_ALREADY_EXIST: 'Order type already exist.',
    // Invoice module
    INVOICE_DETAILS: "Invoice data fetched successfully",
    INVOICE_ADD: "Invoice saved successfully",
    INVALID_INVOICEITEM_ARRAY: "Invoice saved successfully! Saving invoice item failed ,invoice item should be in an valid array format.",
    INVOICE_DELETED_SUCCESS: "Invoice deleted successfully",
    INVOICE_DETAIL_UPDATE: "Invoice details updated successfully",
    //Purchase Module
    PO_LIST: "Purchase order list successfully ",
    PURCHASE_ORDER_ADD: "Purchase order saved successfully",
    PURCHASE_ORDER_UPDATE: "Purchase order updated successfully",
    PURCHASE_ORDER_DETAIL: "Purchase order fetched successfully",
    PO_DELETED_SUCCESS: "Purchase order deleted successfully",
    PO_ATTACH_DELETED_SUCCESS: "Purchase order attachment deleted successfully",
    //servie order Module
    SO_LIST: "Service order list successfully ",
    SERVICE_ORDER_ADD: "Service order saved successfully",
    SERVICE_ORDER_UPDATE: "Service order updated successfully",
    SERVICE_ORDER_DETAIL: "Service order fetched successfully",
    SERVICE_DELETED_SUCCESS: "Service order deleted successfully",
    //Estimate Module
    ESTIMATELIST_FETCH_SUCCESS: 'Estimate list fetched successfully',
    ESTIMATEDATA_FETCH_SUCCESS: 'Estimate data fetched successfully',
    ESTIMATE_ADD_SUCCESS: 'Estimate added successfully',
    ESTIMATE_DETAIL_SUCCESS: 'Estimate detail fetched successfully',
    ESTIMATE_UPDATE_SUCCESS: 'Estimate updated successfully',
    ESTIMATE_DELETED_SUCCESS: 'Estimate deleted successfully',
    FORMAT_ADD_SUCCESS:'Format added successfully',
    FORMAT_UPDATE_SUCCESS:'Format updated successfully',
    PDF_GENRATED_SUCESS:'Pdf genrated successfully',
    //Proposal Module
    PROPOSAL_LIST_FETCH: 'Proposal list fetched successfully',
    PROPOSAL_ADD: 'Proposal added successfully',
    PROPOSAL_DETAIL: 'Proposal detail fetched successfully',
    PROPOSAL_UPDATE: 'Proposal updated successfully',
    PROPOSAL_DELETE: 'Proposal deleted successfully',
    PROPOSAL_SENT_SUCCESS: 'Proposal sent successfully',
    //Project Module
    PROJECT_LIST_FETCH: 'Project list fetched successfully',
    PROJECT_ADD: 'Project added successfully',
    PROJECT_DETAIL: 'Project detail fetched successfully',
    PROJECT_UPDATE: 'Project updated successfully',
    PROJECT_DELETE: 'Project deleted successfully',
    PROJECT_CATEGORY_LIST_FETCHED: 'Category list fetched successfully.',
    PROJECT_TASK_ADD: 'Project task added successfully',
    EXPENSE_LIST: 'Expense list fetch successfully',
    //Item Module
    ITEM_ADDED: "Material added successfully",
    ITEM_UPDATED: "Material updated successfully",
    ITEM_LIST_FETCHED: "Material list fetched successfully",
    ITEM_TYPE_ADDED: "Material type added successfully",
    ITEM_CATEGORY_ADDED: "Material category added successfully",
    ITEM_DELETE_SUCCESS: 'Material deleted successfully',
    ITEM_IMAGE_UPDATED: 'Material image updated successfully',
    ITEM_TYPE_UPDATED: 'Material type updated successfully',
    ITEM_CATEGORY_UPDATED: 'Material category updated successfully',
    TOOLS_LIST: "Tools list fetched successfully",
    TOOLS_ADD: "Tools added successfully",
    INVALID_ITEM: "Material should be in array format",
    //Document Module
    DOCUMENT_FILE_UPDATED: "Document file added successfully",
    DOCUMENT_LIST: "Document list fetched successfully",
    DOCUMENT_ADDED: "Document added successfully",
    DOCUMENT_Update: "Document updated successfully",
    DOCS_TYPE_ADDED: "Document item type added successfully",
    DOCUMENT_CATEGORY_ADDED: "Document category added successfully",
    DOCUMENT_DELETED: "Document deleted successfully",
    //Timer Module
    TIMER_ADD_SUCCESS: "Timer added successfully",
    TIMER_INFO_UPDATED: "Timer info updated successfully",
    TIMER_DETAILS_FETCHED: "Timer details fetched successfully",
    TIMER_LIST_FETCHED: "Timer list fetched successfully",
    TIMER_INFO_DELETED: 'Timer info deleted successfully',
    //Tailgate Module
    TAILGATES_ADD_SUCCESS: "Tailgates added successfully",
    TAILGATES_INFO_UPDATED: "Tailgates info updated successfully",
    TAILGATES_DETAILS_FETCHED: "Tailgates details fetched successfully",
    TAILGATES_LIST_FETCHED: 'Tailgates list fetched successfully.',
    //Event Module
    EVENT_FETCHED_SUCCESS: 'Events list fetched successfully.',
    //Daily Report
    DAILY_REPORT_SUBMITTED: "Daily report submitted successfully.",
    DAILY_REPORT_SENT_SUCCESS: "Daily report sent successfully.",
    ERROR_PDF: "Error while submitted daily report",
    //Labor rate
    laborType_EXIST: 'labour already exist.',
    //Revison 
     REVISION_ITEM_ADDED: "Revision item added successfully",     
     REVISION_ITEM_UPDATED: "Revision item updated successfully",
     REVISION_ITEM_LIST_FETCHED: "Revision item list fetched successfully",    
     REVISION_ITEM_DELETE_SUCCESS: 'Revision item deleted successfully',
     //MEMO
     MEMO_ADDED: "Memo added successfully",
     //export estimate item csv
     EXPORT_ESTIMATEITEM_CSV: "Revision Exported Successfully",
     //User management
     ROLES_UPDATED:"User roles updated successfully",
     File_NO_LONGER_EXIST: 'File no longer exist.',
     TOKEN_VERIFIED:"Token verified successfully",
     TOKEN_INVALID:'Invalid Token!',
     TOKEN_NOT_FOUND:'Token not found!',
     //Signature 
     SIGN_UPDATED:"Signature updated successfully",
     //FileAttachments 
     FILE_RENAME:"File name updated successfully",
     FILE_DELETE:"File deleted successfully",
     FILE_RESTORE:"File restored successfully",
     FILE_RENAME_EXIST:"File name already exists",
     //WorkLog Module
    WORKLOG_ADD_SUCCESS: "WorkLog added successfully",
    WORKLOG_INFO_UPDATED: "WorkLog info updated successfully",
    WORKLOG_DETAILS_FETCHED: "WorkLog details fetched successfully",
    WORKLOG_LIST_FETCHED: "WorkLog list fetched successfully",
    WORKLOG_INFO_DELETED: 'WorkLog info deleted successfully',
    WORKLOG_OTHER_OPTION_EXIST: 'This option already exist',
    WORKLOG_OTHER_OPTION_SUCCESS:'Option Added Successfully',

     SOURCE_ALREADY_EXIST:"Source already exist"
};